### ISSUE TITLE
More missing strings

### ISSUE THREAD

**Issue by philwareham** [textpattern/textpacks#217] opened 2017-07-18 13:50 UTC
Need to add the following (also need to work out what these actually refer to first):

- [x] `alias_is_taken` (provisionally done, might need revisiting with `{alias}` addition)
- [x] `article_tag_illegal_body`
- [x] `assert_callable`
- [x] `assert_length`
- [x] `assert_pattern`
- [x] `assert_string`
- [x] `author_save_failed`
- [x] `default_section_updated`
- [x] `disabled_function`
- [x] `file_download`
- [x] `from_or_to_address_missing`
- [x] `invalid_argument`
- [x] `invalid_expirydate`
- [x] `invalid_header`
- [x] `invalid_token`
- [x] `php_code_disabled_article`
- [x] `php_code_disabled_page`
- [x] `php_code_forbidden_user`
- [x] `pretext_data`
- [x] `reload`
- [x] `sending_failed`
- [x] `tab_site_account`
- [x] `thumbnail_delete_failed`
- [x] `token_expired`
- [x] `unknown`
- [x] `unknown_link`
- [x] `unknown_spam_estimate`
- [x] `variable_name_empty`
- [x] `your_ip_is_blacklisted_by` (this was accidentally deleted - retrieve from 4.6.x branch)

- [x] `bad_login`
- [x] `cgi_header_config`
- [x] `invalid_article_id`
- [x] `missing_db_details`
- [x] `plugin_.($method == delete ? deleted : updated` (is this `plugin_deleted` and `plugin_updated`?)
- [x] `problem_creating_article`
- [x] `problem_deleting_article`
- [x] `problem_getting_articles`
- [x] `problem_retrieving_article`
- [x] `problem_retrieving_article_categories`
- [x] `problem_retrieving_categories`
- [x] `problem_retrieving_category_info`
- [x] `problem_retrieving_sections`
- [x] `problem_saving_article_categories`
- [x] `problem_updating_article`
- [x] `tab_help`
- [x] `tag_.$a)` (need some advice on this - what does it do?)
- [x] `trying_to_assign_unexisting_category_to_the_article`
- [x] `unable_retrieve_template`
- [x] `unable_retrieve_user`
- [x] `unable_set_template`
- [x] `view_.$tabevent._short` (need some advice on this - what does it do?)
- [x] `your_ip_is_blacklisted_by. .$blacklisted)` (is this the same as `your_ip_is_blacklisted_by`?)

**Comment by petecooper** [comment] 2017-08-17 13:24
[ ] `active_language_ui` (Preferences -> Languages – see attached)

<img width="942" alt="screen shot 2017-08-17 at 14 23 46" src="https://user-images.githubusercontent.com/226578/29414511-d40d2f8a-8357-11e7-8df6-d5b83476cad5.png">

**Comment by petecooper** [comment] 2017-09-02 13:35
I've done a couple of passes on `your_ip_is_blacklisted_by` and I think they're all merged from 4.6, so OP can be edited to tick it off.

**Comment by petecooper** [comment] 2017-09-02 13:42
Located `tab_site_account`, added placeholder and English. OP can be edited to tick it off.

<img width="840" alt="screen shot 2017-09-02 at 14 40 29" src="https://user-images.githubusercontent.com/226578/29995936-d3ba4d00-8fec-11e7-9b87-e1ddfd54f2e0.png">

**Comment by petecooper** [comment] 2017-09-02 14:21
`invalid_expirydate` appears when a bogus yyyy-mm-dd expire date is provided. Awaiting merge or results of https://github.com/textpattern/textpattern/pull/930 before I proceed.

<img width="986" alt="screen shot 2017-09-02 at 15 19 07" src="https://user-images.githubusercontent.com/226578/29996213-56d3ecaa-8ff2-11e7-9156-c5473145c8db.png">

**Comment by petecooper** [comment] 2017-09-05 15:26
@philwareham Do you recall where `pretext_data` cropped up as a gTxt? I can't spot it anywhere in the code.

**Comment by philwareham** [comment] 2017-09-05 16:03
@petecooper it appears in `txp_diag.php` around line 627. I have no idea what it translates to though, sorry sir (the missing strings above were generated by a nifty PHP script that @Bloke provided me).

**Comment by petecooper** [comment] 2017-09-07 16:35
Alright, final stretch for those listed at time of writing. 24 of 29 done, 5 to go:

* article_tag_illegal_body
* assert_callable
* assert_length
* assert_pattern
* assert_string

I cannot completely figure out what `article_tag_illegal_body` does.

And the `assert_*` tags are beyond my understanding, too. So, I'm stuck.

I'd really appreciate a quick pointer to explain each one (a sentence is fine), and I'll merge them in.

@bloatware @makss @Bloke -- if you can stop by and leave a note with any advice, I'll do the slotting-in work from there.

Thanks in advance.

**Comment by bloatware** [comment] 2017-09-07 16:44
Hi @petecooper, `article_tag_illegal_body` means *you can not use <txp:article /> tag inside the article body*. Just put it in English...

Not sure for other strings, sorry.

**Comment by petecooper** [comment] 2017-09-07 16:52
Aha! That was on my shortlist as a potential explanation.

I'll get onto that now, thank you @bloatware.

**Comment by petecooper** [comment] 2017-09-07 17:20
@philwareham - Any chance you can rerun the script mentioned in https://github.com/textpattern/textpacks/issues/217#issuecomment-327222977 to find anything new and/or outstanding that's not on the list?

**Comment by Bloke** [comment] 2017-09-07 17:27
@petecooper I've attached the [check-textpack.zip](https://github.com/textpattern/textpacks/files/1285540/check-textpack.zip) file for you to play with. It's quite simple in essence. To run it:

1. Unzip and drop the PHP file in your Textpattern root directory.
2. Run `php check-textpack.php > ../missing.txt` then open up _missing.txt_.

All it does is dump any lang keys it finds defined in the code that are missing from the Textpack.

But since not all "used" keys necessarily need defining in the Textpack, it then dumps a bit more info to help you decide.

Firstly, if the key as defined in the code requires any replacement {parameters} inside the string, they're listed. So if you need to add the string to the Textpack, you know what {replacements} to include in the string.

Then it gives the filename and line number that the first use of this string occurred. So you can go check it out in context if you wish and fix it if it's a bogus entry or if it uses some capitalisation or whatever.

To save you having to go and look in the file itself, the entire line where it was used (the one from the file/line just given) is reproduced as the final item. This allows you to see, for example, if the key was only used in a comment block, or has been commented out in the code (and therefore can safely be ignored). Or if its usage is "programmed" with maybe a prefix/suffix added to it.

Re-run the checker as many times as you like.

**Comment by philwareham** [comment] 2017-11-09 09:25
Hi @petecooper - just wondering if you managed to run Stef's script and ascertain if any other strings were listed as missing. We are very close to getting the languages rework into the Textoattern 4.7 dev branch so I'd like to mop up any major Textpack issues shortly.

**Comment by petecooper** [comment] 2017-11-09 10:08
I'll recheck today or tomorrow -- my dev boxes are offline since the house move and I'm schedule to unpack and reconnect today or tomorrow, so bear with.

**Comment by petecooper** [comment] 2017-11-09 10:09
PS: if there's anyone who can advise what the 4 outstanding strings do, I can swerve them in with some appropriate wordage:

```
 assert_callable
 assert_length
 assert_pattern
 assert_string
```

**Comment by petecooper** [comment] 2017-11-10 20:52
OK, output from `dev` branch checked out to a repo (so, not a live install):

```

...
--> args: 
--> file: textpattern/include/txp_tag.php
--> line: 1854
--> when: $this->build($atts, gTxt('...'));

active_language_ui
--> args: 
--> file: textpattern/include/txp_lang.php
--> line: 118
--> when: tag(gTxt('active_language_ui'), 'label', array('for' => 'language_ui')).

alias_is_taken
--> args: 
--> file: textpattern/vendors/Textpattern/Container/Container.php
--> line: 70
--> when: throw new InvalidArgumentException(gTxt('alias_is_taken'));

article_tag_illegal_body
--> args: 
--> file: textpattern/publish.php
--> line: 666
--> when: trigger_error(gTxt('article_tag_illegal_body'));

assert_callable
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/FilterCallable.php
--> line: 50
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_callable'));

assert_length
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 105
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_length'));

assert_pattern
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 79
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_pattern'));

assert_string
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 50
--> when: throw new Exception(gTxt('assert_string'));

author_save_failed
--> args: 
--> file: textpattern/include/txp_admin.php
--> line: 97
--> when: $msg = array(gTxt('author_save_failed'), E_ERROR);

bad_login
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 887
--> when: return new IXR_Error(100, gTxt('bad_login'));

cgi_header_config
--> args: 
--> file: textpattern/include/txp_diag.php
--> line: 348
--> when: //    $fail['cgi_header_config'] = gTxt('cgi_header_config');

default_section_updated
--> args: 
--> file: textpattern/include/txp_section.php
--> line: 701
--> when: send_script_response(announce(gTxt('default_section_updated')));

disabled_function
--> args: name
--> file: textpattern/vendors/Textpattern/Mail/Adapter/Mail.php
--> line: 205
--> when: throw new Exception(gTxt('disabled_function', array('{name}' => 'mail')));

file_download
--> args: 
--> file: textpattern/publish.php
--> line: 317
--> when: case urldecode(strtolower(urlencode(gTxt('file_download')))):

from_or_to_address_missing
--> args: 
--> file: textpattern/vendors/Textpattern/Mail/Adapter/Mail.php
--> line: 209
--> when: throw new Exception(gTxt('from_or_to_address_missing'));

invalid_argument
--> args: name
--> file: textpattern/vendors/Textpattern/Textfilter/Registry.php
--> line: 116
--> when: throw new \Exception(gTxt('invalid_argument', array('{name}' => 'key')));

invalid_article_id
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 392
--> when: return new IXR_Error(404, gTxt('invalid_article_id'));

invalid_expiredate
--> args: 
--> file: textpattern/include/txp_article.php
--> line: 267
--> when: $msg = array(gTxt('invalid_expiredate'), E_ERROR);

invalid_header
--> args: 
--> file: textpattern/vendors/Textpattern/Mail/Adapter/Mail.php
--> line: 189
--> when: throw new Exception(gTxt('invalid_header'));

invalid_token
--> args: 
--> file: textpattern/include/txp_auth.php
--> line: 356
--> when: $message = array(gTxt('invalid_token'), E_ERROR);

missing_db_details
--> args: 
--> file: textpattern/setup/index.php
--> line: 360
--> when: //                setup_gTxt('missing_db_details'),

plugin_.($method == delete ? deleted : updated
--> args: 
--> file: textpattern/include/txp_plugin.php
--> line: 687
--> when: $message = gTxt('plugin_'.($method == 'delete' ? 'deleted' : 'updated'), array('{name}' => join(', ', $selected)));

pophelp
--> args: 
--> file: textpattern/include/txp_prefs.php
--> line: 777
--> when: '1'  => gTxt('pophelp'),

pretext_data
--> args: 
--> file: textpattern/include/txp_diag.php
--> line: 639
--> when: $out[] = n.gTxt('pretext_data').cs.txpspecialchars(join('', array_slice($pretext_data, 1, 20))).n;

problem_creating_article
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 654
--> when: return new IXR_Error(201, gTxt('problem_creating_article'));

problem_deleting_article
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 581
--> when: return new IXR_Error(206, gTxt('problem_deleting_article'));

problem_getting_articles
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 758
--> when: return new IXR_Error(207, gTxt('problem_getting_articles'));

problem_retrieving_article
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 631
--> when: return new IXR_Error(205, gTxt('problem_retrieving_article'));

problem_retrieving_article_categories
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 829
--> when: return new IXR_Error(211, gTxt('problem_retrieving_article_categories'));

problem_retrieving_categories
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 790
--> when: return new IXR_Error(210, gTxt('problem_retrieving_categories'));

problem_retrieving_category_info
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 842
--> when: // if (!$rs) return new IXR_Error(212, gTxt('problem_retrieving_category_info'));

problem_retrieving_sections
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 423
--> when: return new IXR_Error(203, gTxt('problem_retrieving_sections'));

problem_saving_article_categories
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 913
--> when: return new IXR_Error(214, gTxt('problem_saving_article_categories'));

problem_updating_article
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 874
--> when: return new IXR_Error(201, gTxt('problem_updating_article'));

reload
--> args: 
--> file: textpattern/publish/comment.php
--> line: 383
--> when: RELOAD => gTxt('reload'),

sending_failed
--> args: 
--> file: textpattern/vendors/Textpattern/Mail/Adapter/Mail.php
--> line: 237
--> when: throw new Exception(gTxt('sending_failed'));

set_expire_now
--> args: 
--> file: textpattern/include/txp_article.php
--> line: 2075
--> when: n.tag(gTxt('set_expire_now'), 'label', array('for' => 'expire_now')),

swap_values
--> args: 
--> file: textpattern/include/txp_image.php
--> line: 660
--> when: n.'<a class="thumbnail-swap-size">'.gTxt('swap_values').'</a>'.

tab_help
--> args: 
--> file: textpattern/vendors/Textpattern/Module/Help/HelpAdmin.php
--> line: 159
--> when: pagetop(gTxt('tab_help'));

tab_site_account
--> args: 
--> file: textpattern/include/txp_admin.php
--> line: 600
--> when: hed(gTxt('tab_site_account'), 1, array('class' => 'txp-heading')),

tag_.$a)
--> args: 
--> file: textpattern/lib/txplib_html.php
--> line: 1331
--> when: $out[] = tag(popTag($a, gTxt('tag_'.$a), array('panel' => $event, 'step' => 'build')), 'li');

thumbnail_delete_failed
--> args: 
--> file: textpattern/include/txp_image.php
--> line: 1094
--> when: image_edit(array(gTxt('thumbnail_delete_failed'), E_ERROR), $id);

token_expired
--> args: 
--> file: textpattern/include/txp_auth.php
--> line: 336
--> when: $message = array(gTxt('token_expired'), E_ERROR);

trying_to_assign_unexisting_category_to_the_article
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 899
--> when: return new IXR_Error(213, gTxt('trying_to_assign_unexisting_category_to_the_article'));

unable_retrieve_template
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 501
--> when: return new IXR_Error(208, gTxt('unable_retrieve_template'));

unable_retrieve_user
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 452
--> when: return new IXR_Error(204, gTxt('unable_retrieve_user'));

unable_set_template
--> args: 
--> file: rpc/TXP_RPCServer.php
--> line: 532
--> when: return new IXR_Error(209, gTxt('unable_set_template'));

unknown
--> args: 
--> file: textpattern/include/txp_diag.php
--> line: 646
--> when: $out[] = $f.cs.n.t.(!$checksum ? gTxt('unknown') : $checksum).n;

unknown_link
--> args: 
--> file: textpattern/publish/taghandlers.php
--> line: 722
--> when: trigger_error(gTxt('unknown_link'));

unknown_spam_estimate
--> args: 
--> file: textpattern/publish/comment.php
--> line: 412
--> when: trigger_error(gTxt('unknown_spam_estimate'), E_USER_WARNING);

unregistered_tag
--> args: 
--> file: textpattern/lib/txplib_publish.php
--> line: 592
--> when: trigger_error(gTxt('unregistered_tag'), E_USER_NOTICE);

variable_name_empty
--> args: 
--> file: textpattern/publish/taghandlers.php
--> line: 4897
--> when: trigger_error(gTxt('variable_name_empty'));

view_.$tabevent._short
--> args: 
--> file: textpattern/include/txp_article.php
--> line: 1185
--> when: $link = href(gTxt('view_'.$tabevent.'_short'), '#', array(

your_ip_is_blacklisted_by. .$blacklisted)
--> args: 
--> file: textpattern/publish/taghandlers.php
--> line: 2103
--> when: $out = graf(gTxt('your_ip_is_blacklisted_by'.' '.$blacklisted), ' id="comments_blacklisted"');
```

I'll pare back and see what this means in real terms. Stand by.

**Comment by petecooper** [comment] 2017-11-10 21:00
Pared back and checklist'd for manual checking

- [ ] active_language_ui
- [ ] alias_is_taken
- [ ] article_tag_illegal_body
- [ ] assert_callable
- [ ] assert_length
- [ ] assert_pattern
- [ ] assert_string
- [ ] author_save_failed
- [ ] bad_login
- [ ] cgi_header_config
- [ ] default_section_updated
- [ ] disabled_function
- [ ] file_download
- [ ] from_or_to_address_missing
- [ ] invalid_argument
- [ ] invalid_article_id
- [ ] invalid_expiredate
- [ ] invalid_header
- [ ] invalid_token
- [ ] missing_db_details
- [ ] plugin_.($method == delete ? deleted : updated
- [ ] pophelp
- [ ] pretext_data
- [ ] problem_creating_article
- [ ] problem_deleting_article
- [ ] problem_getting_articles
- [ ] problem_retrieving_article
- [ ] problem_retrieving_article_categories
- [ ] problem_retrieving_categories
- [ ] problem_retrieving_category_info
- [ ] problem_retrieving_sections
- [ ] problem_saving_article_categories
- [ ] problem_updating_article
- [ ] reload
- [ ] sending_failed
- [ ] set_expire_now
- [ ] swap_values
- [ ] tab_help
- [ ] tab_site_account
- [ ] tag_.$a)
- [ ] thumbnail_delete_failed
- [ ] token_expired
- [ ] trying_to_assign_unexisting_category_to_the_article
- [ ] unable_retrieve_template
- [ ] unable_retrieve_user
- [ ] unable_set_template
- [ ] unknown
- [ ] unknown_link
- [ ] unknown_spam_estimate
- [ ] unregistered_tag
- [ ] variable_name_empty
- [ ] view_.$tabevent._short
- [ ] your_ip_is_blacklisted_by. .$blacklisted)

**Comment by petecooper** [comment] 2017-11-10 21:53
@Bloke @philwareham -- this issue is getting a bit unwieldy (probably my fault with numerous edits. OK to continue as-is or shall I shunt the outstanding work to a new issue?

**Comment by petecooper** [comment] 2017-11-11 11:59
Alright, results from `check-textpack.php` analysed and merged. Done.

That leaves us with 4 outstanding:

```
assert_callable
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/FilterCallable.php
--> line: 50
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_callable'));

assert_length
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 105
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_length'));

assert_pattern
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 79
--> when: throw new \Textpattern\Filter\Exception(gTxt('assert_pattern'));

assert_string
--> args: 
--> file: textpattern/vendors/Textpattern/Filter/StringFilter.php
--> line: 50
--> when: throw new Exception(gTxt('assert_string'));
```

I'm gonna need a bit of help with this, even just a sentence or two with pointers, because I don't know what they do _at all_ right now.

@makss @bloatware @Bloke - any feedback you can give me is greatly appreciated.

**Comment by Bloke** [comment] 2017-11-11 12:57
These are just used to throw error messages that certain types of content are expected (e.g. a string or a callable function) but Txp received something unexpected instead and gave up. So in theory, shouldn't be seen in core!

**Comment by bloatware** [comment] 2017-11-11 12:59
> So in theory, shouldn't be seen in core!

+1

**Comment by petecooper** [comment] 2017-11-11 13:01
Is it fair to say they don't need Textpack entries, then?

**Comment by Bloke** [comment] 2017-11-11 13:17
Well if a plugin triggers them by doing something strange, then it can be handy. But again, this sort of thing should be caught in development + testing. If you tell Txp to expect a number (integer) or a specific regex and a user supplies something else you can throw an exception. Not a very friendly way of doing things though - should catch those and throw a prettier message.

I'm honestly not sure what those strings are doing in the Textpacks. They're system generated messages and if they are triggered, we've done our jobs badly!

**Comment by petecooper** [comment] 2017-11-11 13:26
Thanks, @Bloke - appreciated. They're not in Textpacks at all right now, they are (were) on the candidate list for gTxt that appears in the code but doesn't have an entry in Textpacks _yet_.

If I go with something generic like:

```
assert_callable => Unexpected content: expected callable function.
assert_length => Unexpected length mismatch
assert_pattern=> Unexpected pattern mismatch
assert_string=> Unexpected string mismatch
```
…would that suffice?

**Comment by Bloke** [comment] 2017-11-11 13:29
Sure, sounds great as a starter for ten, thanks.

**Comment by petecooper** [comment] 2017-11-11 13:36
Full house, job done.

**Closed by petecooper** 2017-11-11 13:36 UTC
